# Copyright 2020 Intel Corporation.
#
# THIS SOFTWARE MAY CONTAIN PREPRODUCTION CODE AND IS PROVIDED BY THE
# COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# - Try to find libintelfpga
# Once done, this will define
#
#  libintelfpga_FOUND - system has libintelfpga
#  libintelfpga_INCLUDE_DIRS - the libpae-c include directories
#  libintelfpga_LIBRARIES - link these to use libintelfpga

find_package(PkgConfig)

# Include dir
find_path(libintelfpga_INCLUDE_DIRS
  NAMES CL/cl_ext_intelfpga.h
  PATHS
  $ENV{INTELFPGAOCLSDKROOT}/host/include
)

# The library itself
find_library(libintelfpga_LIBRARIES
  NAMES alteracl
  PATHS
  $ENV{INTELFPGAOCLSDKROOT}/host/linux64/lib
)

if(libintelfpga_LIBRARIES AND libintelfpga_INCLUDE_DIRS)
  set(libintelfpga_FOUND true)
endif(libintelfpga_LIBRARIES AND libintelfpga_INCLUDE_DIRS)
