#!/bin/bash

## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: MIT

###############################################################################
# Script removes packages and configuration settings added during install
###############################################################################

if [ -n "$OFS_ASP_ENV_DEBUG_UNINSTALL_SCRIPT" ]; then
  set -x
fi

###############################################################################
# Remove config files that were set during install
###############################################################################
delete_config() {
  echo "Removing configuration files"
  sudo rm /etc/security/limits.d/90-intel-fpga-opencl-limits.conf
  sudo rm /etc/udev/rules.d/90-intel-fpga-opencl.rules
  sudo rm /etc/sysctl.d/intel-fpga-opencl-sysctl.conf
}


echo -n "Do you want to remove oneAPI-ASP configuration settings [Y/n] "
read answer
if [ "$answer" != "n" ]; then
  echo "Deleting OPAE config files"
  delete_config
fi

echo "OFS oneAPI-ASP uninstall complete"
