#! /bin/bash

## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: MIT

###############################################################################
# Scripts initialized OFS card with default aocx that ships with BSP. This
# allows other OpenCL programs to access BSP functionality before loading
# application specific aocx.
###############################################################################

SCRIPT_DIR_PATH="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
BSP_ROOT="$(readlink -e "$SCRIPT_DIR_PATH/../..")"

device_name="$1"
board_variant="$2"

aocx_file="$BSP_ROOT/bringup/aocxs/$board_variant.aocx"
if [ ! -f "$aocx_file" ]; then
  echo "Error: cannot find '$aocx_file' to initialize $board_variant"
  exit 1
fi

"$BSP_ROOT/linux64/libexec/setup_permissions.sh"

"$BSP_ROOT/linux64/libexec/program" "$device_name" "unused_param" "$aocx_file"
return_val=$?
exit $return_val
