#!/bin/bash

# Copyright 2020 Intel Corporation.
#
# THIS SOFTWARE MAY CONTAIN PREPRODUCTION CODE AND IS PROVIDED BY THE
# COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


if [ -n "$OFS_BSP_ENV_DEBUG_INSTALL_SCRIPT" ]; then
  set -x
fi

BSP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../.. && pwd )"

###############################################################################
# Check return code and exit with error message if not 0
# Arguments:
#   Return code to check
#   Error message printed on failure
###############################################################################
check_res() {
  local ret_code="$1"
  local msg="$2"
  if [ "$ret_code" -ne 0 ]; then
    echo "Error: $msg" >&2
    exit "$ret_code"
  fi
}

###############################################################################
# Print error message and exit
# Arguments
#   Error message to print
###############################################################################
error() {
  echo "Error: $1" >&2
  exit 1
}

###############################################################################
# Call script to configure permissions needed for using OFS card
###############################################################################
configure_permission() {
  /usr/bin/env bash "$BSP_ROOT/linux64/libexec/setup_permissions.sh"
  check_res $? "Error: 'setup_permissions.sh' script failed"
}


###############################################################################
# Main script logic
###############################################################################

if [ -z "$OFS_BSP_ENV_NO_PERMISSIONS_INSTALL" ]; then
  configure_permission
fi

echo "Intel OFS OpenCL BSP install complete."
echo "Run 'aocl diagnose' to list devices or 'aocl initialize <dev_name> to load default aocx"
