#!/bin/bash

# Copyright 2020 Intel Corporation.
#
# THIS SOFTWARE MAY CONTAIN PREPRODUCTION CODE AND IS PROVIDED BY THE
# COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

###############################################################################
# Script removes packages and configuration settings added during install
###############################################################################

if [ -n "$OFS_BSP_ENV_DEBUG_UNINSTALL_SCRIPT" ]; then
  set -x
fi

###############################################################################
# Remove config files that were set during install
###############################################################################
delete_config() {
  echo "Removing configuration files"
  sudo rm /etc/security/limits.d/90-intel-fpga-opencl-limits.conf
  sudo rm /etc/udev/rules.d/90-intel-fpga-opencl.rules
  sudo rm /etc/sysctl.d/intel-fpga-opencl-sysctl.conf
}


echo -n "Do you want to remove OpenCL BSP configuration settings [Y/n] "
read answer
if [ "$answer" != "n" ]; then
  echo "Deleting OPAE config files"
  delete_config
fi

echo "OFS OpenCL BSP uninstall complete"
